services:

  app:
    build:
      context: ./
    restart: 'no'
    environment:
      DB_HOST: dgraph_standalone:8080
      BATCH_INTERVAL: 30

  db:
    hostname: dgraph_standalone
    image: dgraph/standalone:v22.0.2
    restart: 'no'
    ports:
      - '8080:8080'
      - '9080:9080'

  db_init:
    image: ghcr.io/sustainability-zhaw/dgraph-schema:sha-e3c06cf
    restart: 'no'
    environment:
      DGRAPH_SERVER: http://dgraph_standalone:8080
      SAMPLE_DATA: plain_pubs

  db_browser:
    image: dgraph/ratel:v21.12.0
    restart: 'no'
    ports:
      - '8000:8000'
