services:

  app:
    build:
      context: ./
    restart: 'no'
    networks:
      - dgraphnet
    depends_on:
      db_keywords:
        condition: service_completed_successfully 
    environment:
      DB_HOST: db:8080
      BATCH_INTERVAL: 30

  db:
    # hostname: dgraph_standalone # Hardcoded in db_init entrypoint.sh
    image: dgraph/standalone:v22.0.2
    restart: 'no'
    networks:
      - dgraphnet
    ports:
      - '8080:8080'
      - '9080:9080'

  db_init:
    image: ghcr.io/sustainability-zhaw/dgraph-schema:sha-520337d
    restart: 'no'
    networks:
      - dgraphnet
    environment:
      DGRAPH_SERVER: http://db:8080
      SAMPLE_DATA: plain_pubs

  db_keywords:
    image: ghcr.io/sustainability-zhaw/keywords:sha-3c3cd20
    restart: 'no'
    networks:
      - dgraphnet
    depends_on:
      db_init:
        condition: service_completed_successfully 
    environment:
      DB_URI: http://db:8080/graphql

  db_browser:
    image: dgraph/ratel:v21.12.0
    restart: 'no'
    networks:
      - dgraphnet
    ports:
      - '8000:8000'

networks:
  dgraphnet:
