FROM python:3.12.1-slim-bookworm

ENV BATCH_INTERVAL=180
ENV BATCH_SIZE=100
ENV LOG_LEVEL=DEBUG

RUN groupadd -r app && \
    useradd --no-log-init -r -m -g app app


COPY requirements-spacy.txt .

RUN apt update && \
    apt install -y --no-install-recommends \
        build-essential \
        cmake \
        libpq-dev \
        libxml2-dev \
        libxslt1-dev \
        libffi-dev \
        libssl-dev \
        libblas-dev \
        liblapack-dev \
        libatlas-base-dev \
        gfortran \
        git \
        curl \
        wget \
        unzip \
        ca-certificates \
        locales \
        locales-all \
        && \
    rm -rf /var/lib/apt/lists/* && \
    apt clean

RUN pip install --root-user-action=ignore --no-cache-dir -r requirements-spacy.txt && \
    rm requirements-spacy.txt 

# Spacy models
RUN python -m spacy download en_core_web_sm && \
    python -m spacy download fr_core_news_sm && \
    python -m spacy download de_core_news_sm && \
    python -m spacy download it_core_news_sm 

# RUN python -m spacy download en_core_web_trf && \
#     python -m spacy download fr_dep_news_trf && \
#     python -m spacy download de_dep_news_trf && \
#     python -m spacy download it_core_news_lg

COPY src/ /app/
RUN chmod -R 775 /app

USER app

WORKDIR /app

CMD [ "python", "main.py" ]
